#             _                  _     _
#            (_)                | |   | |
#   _ __ ___  _ _ __   ___  __ _| |__ | | ___
#  | '_ ` _ \| | '_ \ / _ \/ _` | '_ \| |/ _ \
#  | | | | | | | | | |  __/ (_| | |_) | |  __/
#  |_| |_| |_|_|_| |_|\___|\__,_|_.__/|_|\___|
#   ___ _ __   __ ___      ___ __   ___ _ __ ___
#  / __| '_ \ / _` \ \ /\ / / '_ \ / _ \ '__/ __|
#  \__ \ |_) | (_| |\ V  V /| | | |  __/ |  \__ \
#  |___/ .__/ \__,_| \_/\_/ |_| |_|\___|_|  |___/
#      | |
#      |_|
#

require_permission:
  # Require the permission `mineablespawners.break` to break a spawner?
  # Default: true
  spawner_break: true

  # Require `mineablespawners.nosilk` to mine a spawner with a pick that doesn't have Silk Touch?
  # Default: true
  no_silk: true

  # Require the permission `mineablespawners.spawner` to use the /spawner command?
  # Default: true
  spawner_command: true

  # Require the permission `mineablespawners.give` to use the /spawnergive command?
  # Default: true
  spawnergive_command: true

  # Require the permission `mineablespawners.eggchange` to use spawn eggs to change spawner types
  # Default: true
  egg_change: true

# Don't change this
version: 1.3.3